DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0Ab32j91bknHrQh95n7_w-61OCBtSUXhL9PYZGBWnhl_uSwlIrEe2XFnPxXjvBA-fOpdLug" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
